import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";
import { Toaster } from "@/app/components/ui/sonner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GrocerGO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen w-screen m-0 p-0">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen m-0 p-0 flex flex-col`}
      >

          <Navbar />

          <main className="size-full flex-1">
            {children}
          </main>
          
          <Toaster/>
      </body>
    </html>
  );
}
